# fly.toml app configuration file generated for skialpp on 2023-11-07T16:15:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "skialpp"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
